name: 'retendo-network'
services:
  nginx:
    image: nginx:mainline-alpine
    restart: no
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./config/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./config/nginx
        target: /etc/nginx/conf.d/
        read_only: true
    networks:
      default:
      internal:

  mongodb:
    image: mongo:latest
    restart: no
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - type: bind
        source: ./config/mongod.conf
        target: /etc/mongod.conf
        read_only: true
      - type: volume
        source: mongodb-database
        target: /data/db
    networks:
      internal:
    command: --config "/etc/mongod.conf" --replSet rs

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb
    restart: no
    ports:
      - 127.0.0.1:8082:8082
    networks:
      internal:
    environment:
      - PORT=8082
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true

  redis:
    image: redis:alpine
    restart: no
    volumes:
      - type: volume
        source: redis-data
        target: /data
    networks:
      internal:
    command: redis-server --save 60 1

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    depends_on:
      - redis
    restart: no
    ports:
      - 127.0.0.1:8086:8086
    networks:
      internal:
    environment:
      - PORT=8086
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  postgres:
    image: postgres:alpine
    restart: no
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - type: volume
        source: postgres-database
        target: /var/lib/postgresql/data
    networks:
      internal:
    environment:
      - POSTGRES_USER=postgres_retendo
      - POSTGRES_PASSWORD=

  adminer:
    image: adminer:latest
    depends_on:
      - postgres
    restart: no
    ports:
      - 127.0.0.1:8085:8080
    volumes:
      - type: bind
        source: ./config/adminer-login-servers.php
        target: /var/www/html/plugins-enabled/login-servers.php
        read_only: true
    networks:
      internal:
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  boss:
    image: node:18-alpine
    restart: no
    working_dir: /app
    volumes:
      - ./repos/BOSS:/app 
      - /app/node_modules
    ports:
      - "86:86"
    command: sh -c "npm install && npm run build && npm run start"
    networks:
      internal:

  nintendo-wiki:
    image: node:18-alpine
    restart: no
    working_dir: /app
    volumes:
      - ./repos/nintendo-wiki:/app 
      - /app/node_modules
    ports:
      - "87:87"
    command: sh -c "npm install && npm run start"
    networks:
      internal:

  website:
    build: ./repos/website
    depends_on:
      - account
      - mongodb
    restart: no
    ports:
      - 127.0.0.1:82:82
    volumes:
      - type: bind
        source: ./config/adminer-login-servers.php
        target: /var/www/html/plugins-enabled/login-servers.php
        read_only: true
    command: sh -c "npm install && npm run start"
    networks:
      internal:

  account:
    build: ./repos/account
    depends_on:
      - nginx
      - mongodb
      - redis
    restart: no
    ports:
      - 127.0.0.1:83:83
    command: sh -c "npm install && npm run start"
    networks:
      internal:

  mitmproxy-retendo:
    image: mitmproxy/mitmproxy:latest
    # build: ./repos/mitmproxy-retendo
    restart: no
    ports:
      - 8080:8080
      - 127.0.0.1:8081:8081
    volumes:
      - type: volume
        source: mitmproxy-retendo-data
        target: /home/mitmproxy/.mitmproxy
    command: mitmweb --web-host 0.0.0.0
    tty: true

  friends:
    build: ./repos/friends
    depends_on:
      - account
      - postgres
    restart: no
    ports:
      # Go delve debugger
      - 127.0.0.1:2345:2345
      # Authentication server
      - 6000:6000/udp
      # Secure server
      - 6001:6001/udp
    networks:
      internal:
    environment:
      - PN_FRIENDS_ACCOUNT_GRPC_HOST=account
      - PN_FRIENDS_ACCOUNT_GRPC_PORT=5000
      - PN_FRIENDS_GRPC_SERVER_PORT=5001
      - PN_FRIENDS_AUTHENTICATION_SERVER_PORT=6000
      - PN_FRIENDS_SECURE_SERVER_PORT=6001
      - PN_FRIENDS_ACCOUNT_GRPC_API_KEY=
      - PN_FRIENDS_CONFIG_DATABASE_URI=
      - PN_FRIENDS_CONFIG_AUTHENTICATION_PASSWORD=
      - PN_FRIENDS_CONFIG_SECURE_PASSWORD=
      - PN_FRIENDS_CONFIG_GRPC_API_KEY=
      - PN_FRIENDS_CONFIG_AES_KEY=
      - PN_FRIENDS_SECURE_SERVER_HOST=

  pikmin-3:
    build: ./repos/pikmin-3
    depends_on:
      - account
      - postgres
    restart: unless-stopped
    ports:
      # Go delve debugger
      - 127.0.0.1:2351:2349
      # Authentication server
      - 6010:6010/udp
      # Secure server
      - 6011:6011/udp
    networks:
      internal:
    environment:
      - PN_PIKMIN3_AUTHENTICATION_SERVER_PORT=6010
      - PN_PIKMIN3_SECURE_SERVER_PORT=6011
      - PN_PIKMIN3_ACCOUNT_GRPC_HOST=account
      - PN_PIKMIN3_ACCOUNT_GRPC_PORT=5000
      - PN_PIKMIN3_ACCOUNT_GRPC_API_KEY=
      - PN_PIKMIN3_POSTGRES_URI=
      - PN_PIKMIN3_KERBEROS_PASSWORD=
      - PN_PIKMIN3_SECURE_SERVER_HOST=


volumes:
  mitmproxy-retendo-data:
  mongodb-database:
  redis-data:
  postgres-database:

networks:
  internal:
    driver: bridge