name: 'retendo-network'
services:
  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./config/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./config/nginx/
        target: /etc/nginx/conf.d/
    networks:
      default:
      internal:

networks:
  internal:
    driver: bridge