name: 'retendo-network'
services:

  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./config/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./config/nginx
        target: /etc/nginx/conf.d/
        read_only: true
    networks:
      default:
      internal:

  boss:
    image: node:18-alpine
    restart: always
    working_dir: /app
    volumes:
      - ./repos/BOSS:/app 
      - ./config:/app/config
      - /app/node_modules
    ports:
      - "9233:9233"
    command: sh -c "npm install && npm run build && npm run start"
    networks:
      internal:

networks:
  internal:
    driver: bridge