name: 'retendo-network'
services:

  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./config/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./config/nginx
        target: /etc/nginx/conf.d/
        read_only: true
    networks:
      default:
      internal:

  boss:
    build: ./repos/BOSS
    restart: always
    ports:
      - 127.0.0.1:9233:9233
    networks:
      internal:
    command: ["node", "--inspect=0.0.0.0:9233", "."]

networks:
  internal:
    driver: bridge